// priority: 500
AStages.addRestrictionForDimension('infinity/nexus', 'ftb_can_enter_nexus', 'infinity:nexus')
AStages.addRestrictionForDimension('main/dimensional_worm_nether', 'ftb_server_ban_nether', 'minecraft:the_nether')
    .setReverse(true)

AStages.addRestrictionForDimension('main/final_dim_restrict_1', FTBFinalDimRestrict1, 'infinity:infinity')
    .setReverse(true)
    .setMaxStayTimer(ATime('5m'))
AStages.addRestrictionForDimension('main/final_dim_restrict_2', FTBFinalDimRestrict2, 'infinity:infinity')
    .setReverse(true)
    .setMaxStayTimer(ATime('10s'))
AStages.addRestrictionForDimension('main/final_dim_restrict_3_infinity', FTBFinalDimRestrict3, 'infinity:infinity')
    .setReverse(true)
    .setMaxStayTimer(ATime('10s'))
AStages.addRestrictionForDimension('main/final_dim_restrict_3_end', FTBFinalDimRestrict3, 'minecraft:the_end')
    .setReverse(true)
    .setMaxStayTimer(ATime('10s'))
AStages.addRestrictionForDimension('main/final_dim_restrict_3_nether', FTBFinalDimRestrict3, 'minecraft:the_nether')
    .setReverse(true)
    .setMaxStayTimer(ATime('10s'))
AStages.addRestrictionForDimension('main/final_dim_restrict_3_pocket_dim', FTBFinalDimRestrict3, 'irons_spellbooks:pocket_dimension')
    .setReverse(true)
    .setMaxStayTimer(ATime('10s'))
AStages.addRestrictionForDimension('main/final_dim_restrict_3_oath', FTBFinalDimRestrict3, 'kubejs:oath')
    .setReverse(true)
    .setMaxStayTimer(ATime('10s'))
AStages.addRestrictionForDimension('main/final_dim_restrict_3_past', FTBFinalDimRestrict3, 'graveyard:past')
    .setReverse(true)
    .setMaxStayTimer(ATime('10s'))