// priority: 500
RegistryOrgan('kubejs:fireproof_appendix').setRank(0).addScore('chestcavity:luck', 0.5).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_intestine').setRank(0).addScore('chestcavity:nutrition', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_heart').setRank(0).addScore('chestcavity:health', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_kidney').setRank(0).addScore('chestcavity:filtration', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_liver').setRank(0).addScore('chestcavity:detoxification', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_lung').setRank(0).addScore('chestcavity:breath_recovery', 0.75).addScore('chestcavity:breath_capacity', 0.75).addScore('chestcavity:endurance', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_muscle').setRank(0).addScore('chestcavity:strength', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_rib').setRank(0).addScore('chestcavity:defense', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_spine').setRank(0).addScore('chestcavity:nerves', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_spleen').setRank(0).addScore('chestcavity:metabolism', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:fireproof_stomach').setRank(0).addScore('chestcavity:digestion', 0.75).addScore('chestcavity:fire_resistant', 0.5).setCanSpawn(true)
