// priority: 2000
const PillagerAdvanceArenaPattern = $BlockPatternBuilder.start()
    .aisle('        BBBBB        ', '                     ',)
    .aisle('      BBSYSYSBB      ', '                     ',)
    .aisle('    BBSSSYSYSSSBB    ', '                     ',)
    .aisle('   BSSSSYYSYYSSSSB   ', '                     ',)
    .aisle('  BSSSSSYSSSYSSSSSB  ', '                     ',)
    .aisle('  BSSSSSYYSYYSSSSSB  ', '                     ',)
    .aisle(' BSSSSSSSYSYSSSSSSSB ', '                     ',)
    .aisle(' BSSSSSSYESEYSSSSSSB ', '                     ',)
    .aisle('BSSYYYSYY#G#YYSYYYSSB', '        L   L        ',)
    .aisle('BYYYSYYE#TTT#EYYSYYYB', '                     ',)
    .aisle('BSSSSSSSGTETGSSSSSSSB', '          @          ',)
    .aisle('BYYYSYYE#TTT#EYYSYYYB', '                     ',)
    .aisle('BSSYYYSYY#G#YYSYYYSSB', '        L   L        ',)
    .aisle(' BSSSSSSYESEYSSSSSSB ', '                     ',)
    .aisle(' BSSSSSSSYSYSSSSSSSB ', '                     ',)
    .aisle('  BSSSSSYYSYYSSSSSB  ', '                     ',)
    .aisle('  BSSSSSYSSSYSSSSSB  ', '                     ',)
    .aisle('   BSSSSYYSYYSSSSB   ', '                     ',)
    .aisle('    BBSSSYSYSSSBB    ', '                     ',)
    .aisle('      BBSYSYSBB      ', '                     ',)
    .aisle('        BBBBB        ', '                     ',)
    .where('B', $BlockInWorld.hasState((state) => state.is('minecraft:dark_oak_log')))
    .where('S', $BlockInWorld.hasState((state) => state.is('minecraft:spruce_planks')))
    .where('Y', $BlockInWorld.hasState((state) => state.is('minecraft:dark_oak_planks')))
    .where('T', $BlockInWorld.hasState((state) => state.is('minecraft:dark_oak_stairs')))
    .where('G', $BlockInWorld.hasState((state) => state.is('minecraft:gold_block')))
    .where('E', $BlockInWorld.hasState((state) => state.is('minecraft:emerald_block')))
    .where('#', $BlockInWorld.hasState((state) => state.is('create:experience_block')))
    .where('L', $BlockInWorld.hasState((state) => state.is('minecraft:lantern')))
    .where('@', $BlockInWorld.hasState((state) => state.is('minecraft:crying_obsidian')))
    .build()

const PillagerBasicArenaPattern = $BlockPatternBuilder.start()
    .aisle('        BBBBB        ', '                     ',)
    .aisle('      BBSSSSSBB      ', '                     ',)
    .aisle('    BBSSSSSSSSSBB    ', '                     ',)
    .aisle('   BSSSSSSSSSSSSSB   ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSYSYSSSSSSB  ', '                     ',)
    .aisle(' BSSSSSSSYSYSSSSSSSB ', '                     ',)
    .aisle(' BSSSSSSYCSCYSSSSSSB ', '                     ',)
    .aisle('BSSSSSSYYCICYYSSSSSSB', '                     ',)
    .aisle('BSSSSYYCCTTTCCYYSSSSB', '                     ',)
    .aisle('BSSSSSSSITETISSSSSSSB', '          @          ',)
    .aisle('BSSSSYYCCTTTCCYYSSSSB', '                     ',)
    .aisle('BSSSSSSYYCICYYSSSSSSB', '                     ',)
    .aisle(' BSSSSSSYCSCYSSSSSSB ', '                     ',)
    .aisle(' BSSSSSSSYSYSSSSSSSB ', '                     ',)
    .aisle('  BSSSSSSYSYSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle('   BSSSSSSSSSSSSSB   ', '                     ',)
    .aisle('    BBSSSSSSSSSBB    ', '                     ',)
    .aisle('      BBSSSSSBB      ', '                     ',)
    .aisle('        BBBBB        ', '                     ',)
    .where('B', $BlockInWorld.hasState((state) => state.is('minecraft:dark_oak_log')))
    .where('S', $BlockInWorld.hasState((state) => state.is('minecraft:spruce_planks')))
    .where('Y', $BlockInWorld.hasState((state) => state.is('minecraft:dark_oak_planks')))
    .where('C', $BlockInWorld.hasState((state) => state.is('minecraft:waxed_copper_block')))
    .where('T', $BlockInWorld.hasState((state) => state.is('minecraft:dark_oak_stairs')))
    .where('I', $BlockInWorld.hasState((state) => state.is('minecraft:iron_block')))
    .where('E', $BlockInWorld.hasState((state) => state.is('minecraft:emerald_block')))
    .where('@', $BlockInWorld.hasState((state) => state.is('minecraft:crying_obsidian')))
    .build()