// priority: 2000
const SecretArenaPattern = $BlockPatternBuilder.start()
    .aisle('        BBBBB        ', '                     ',)
    .aisle('      BBSBYBSBB      ', '                     ',)
    .aisle('    BBSSSBYBSSSBB    ', '                     ',)
    .aisle('   BSSSSSBYBSSSSSB   ', '                     ',)
    .aisle('  BSSSSSWBYBWSSSSSB  ', '                     ',)
    .aisle('  BSSSWWYBYBYWWSSSB  ', '                     ',)
    .aisle(' BSSSWYYYOYOYYYWSSSB ', '                     ',)
    .aisle(' BSSSWY&&PYP&&YWSSSB ', '                     ',)
    .aisle('BSSSWYY&@@Y@@&YYWSSSB', '                     ',)
    .aisle('BBBBBBOP@YYY@POBBBBBB', '                     ',)
    .aisle('BYYYYYYYYYEYYYYYYYYYB', '          @          ',)
    .aisle('BBBBBBOP@YYY@POBBBBBB', '                     ',)
    .aisle('BSSSWYY&@@Y@@&YYWSSSB', '                     ',)
    .aisle(' BSSSWY&&PYP&&YWSSSB ', '                     ',)
    .aisle(' BSSSWYYYOYOYYYWSSSB ', '                     ',)
    .aisle('  BSSSWWYBYBYWWSSSB  ', '                     ',)
    .aisle('  BSSSSSWBYBWSSSSSB  ', '                     ',)
    .aisle('   BSSSSSBYBSSSSSB   ', '                     ',)
    .aisle('    BBSSSBYBSSSBB    ', '                     ',)
    .aisle('      BBSBYBSBB      ', '                     ',)
    .aisle('        BBBBB        ', '                     ',)
    .where('B', $BlockInWorld.hasState((state) => state.is('cataclysm:chiseled_obsidian_bricks')))
    .where('S', $BlockInWorld.hasState((state) => state.is('minecraft:gilded_blackstone')))
    .where('Y', $BlockInWorld.hasState((state) => state.is('minecraft:sculk')))
    .where('W', $BlockInWorld.hasState((state) => state.is('create:rose_quartz_tiles')))
    .where('O', $BlockInWorld.hasState((state) => state.is('cataclysm:ancient_metal_block')))
    .where('P', $BlockInWorld.hasState((state) => state.is('vanillabackport:chiseled_resin_bricks')))
    .where('&', $BlockInWorld.hasState((state) => state.is('tconstruct:enderbark_planks_stairs')))
    .where('E', $BlockInWorld.hasState((state) => state.is('create:experience_block')))
    .where('@', $BlockInWorld.hasState((state) => state.is('minecraft:crying_obsidian')))
    .build()