// priority: 500
RegistryOrgan('kubejs:rotten_appendix').setRank(0).addScore('chestcavity:luck', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_intestine').setRank(0).addScore('chestcavity:nutrition', 0.75).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_heart').setRank(0).addScore('chestcavity:health', 0.75).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_kidney').setRank(0).addScore('chestcavity:filtration', 0.75).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_liver').setRank(0).addScore('chestcavity:detoxification', 0.75).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_lung').setRank(0).addScore('chestcavity:breath_recovery', 0.75).addScore('chestcavity:breath_capacity', 0.75).addScore('chestcavity:endurance', 0.75).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_muscle').setRank(0).addScore('chestcavity:strength', 1.5).addScore('chestcavity:speed', -0.25).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_rib').setRank(0).addScore('chestcavity:defense', 0.75).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_spine').setRank(0).addScore('chestcavity:nerves', 0.75).addScore('chestcavity:speed', -0.25).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_spleen').setRank(0).addScore('chestcavity:metabolism', 0.75).setCanSpawn(true)
RegistryOrgan('kubejs:rotten_stomach').setRank(0).addScore('chestcavity:digestion', 0.75).setCanSpawn(true)
