// priority: 500
TetraJSEvents.registerStatBar(event => {
    event.registerEffectBar('kubejs:fabric_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:fabric_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:fabric_inspiration', 1, 0))
    event.registerEffectBar('kubejs:fibre_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:fibre_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:fibre_inspiration', 1, 0))
    event.registerEffectBar('kubejs:skin_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:skin_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:skin_inspiration', 1, 0))
    event.registerEffectBar('kubejs:scale_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:scale_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:scale_inspiration', 1, 0))
    event.registerEffectBar('kubejs:wood_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:wood_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:wood_inspiration', 1, 0))
    event.registerEffectBar('kubejs:bone_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:bone_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:bone_inspiration', 1, 0))
    event.registerEffectBar('kubejs:metal_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:metal_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:metal_inspiration', 1, 0))
    event.registerEffectBar('kubejs:stone_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:stone_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:stone_inspiration', 1, 0))
    event.registerEffectBar('kubejs:gem_inspiration')
        .setMin(0)
        .setMax(10)
        .setLabelGetter('integerlabel')
        .setStatGetter(TetraStatBarHelper.effectLevel('kubejs:gem_inspiration', 1, 0))
        .addIntegerTooltip(TetraStatBarHelper.effectLevel('kubejs:gem_inspiration', 1, 0))
})