// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:cherry_bone')
    .addDefault(Text.translatable('tooltips.kubejs.cherry_bone.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.cherry_bone.alt.1', VitaToxinsHover, VitaToxinsHover))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.cherry_bone.ctrl.1', VitaToxinsHover, PutridToxinsHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:crimson_brain')
    .addDefault(Text.translatable('tooltips.kubejs.crimson_brain.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.crimson_brain.alt.1', PutridToxinsHover, PutridToxinsHover))
    .addAlt(Text.translatable('tooltips.kubejs.crimson_brain.alt.2'))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.crimson_brain.ctrl.1', PutridToxinsHover, PutridToxinsHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:hop_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.hop_kidney.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.hop_kidney.alt.1', KeyActiveHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:lily_pad_lung')
    .addDefault(Text.translatable('tooltips.kubejs.lily_pad_lung.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lily_pad_lung.alt.1', PutridToxinsHover, PutridToxinsHover))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.lily_pad_lung.ctrl.1', PutridToxinsHover, PutridToxinsHover))
)


RegistryOrganTooltip(new MultiStateTooltip('kubejs:pitcher_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.pitcher_stomach.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.pitcher_stomach.alt.1', FullChargeAttackHover))
    .addAlt(Text.translatable('tooltips.kubejs.pitcher_stomach.alt.2', PutridToxinsHover))
    .addAlt(Text.translatable('tooltips.kubejs.pitcher_stomach.alt.3'))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.pitcher_stomach.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:twisting_weeping_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.alt.1', KeyActiveHover))
    .addAlt(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.alt.2', PutridToxinsHover))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.ctrl.1', PutridToxinsHover))
    .addCtrl(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.ctrl.2', PutridToxinsHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:vita_berry')
    .addDefault(Text.translatable('tooltips.kubejs.vita_berry.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.vita_berry.alt.1', VitaToxinsHover))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.vita_berry.ctrl.1', VitaToxinsHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:vita_rose_liver')
    .addDefault(Text.translatable('tooltips.kubejs.vita_rose_liver.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.vita_rose_liver.alt.1', VitaToxinsHover, VitaToxinsHover))
    .addAlt(Text.translatable('tooltips.kubejs.vita_rose_liver.alt.2', VitaToxinsHover))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.vita_rose_liver.ctrl.1', VitaToxinsHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:vita_sunflower')
    .addDefault(Text.translatable('tooltips.kubejs.vita_sunflower.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.vita_sunflower.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.vita_sunflower.alt.2', VitaToxinsHover, VitaToxinsHover))
    .addCtrl(FertileSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.vita_sunflower.ctrl.1', VitaToxinsHover))
    .addCtrl(Text.translatable('tooltips.kubejs.vita_sunflower.ctrl.2', VitaToxinsHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:rootling_ectoplasm')
    .addDefault(Text.translatable('tooltips.kubejs.rootling_ectoplasm.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rootling_ectoplasm.alt.1', Text.gold('9 * 9')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:foliaath_stem')
    .addDefault(Text.translatable('tooltips.kubejs.foliaath_stem.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.foliaath_stem.alt.1', Text.gold('3')))
)