// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ender_guardian_spine')
    .addDefault(Text.translatable('tooltips.kubejs.ender_guardian_spine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ender_guardian_spine.alt.1', Text.gold('10')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:bookwyrm_star_gem')
    .addDefault(Text.translatable('tooltips.kubejs.bookwyrm_star_gem.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.bookwyrm_star_gem.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:dying_heart')
    .addDefault(Text.translatable('tooltips.kubejs.dying_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.dying_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.dying_heart.alt.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:warden_core')
    .addDefault(Text.translatable('tooltips.kubejs.warden_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.warden_core.alt.1', KeyActiveHover))
    .addAlt(Text.translatable('tooltips.kubejs.warden_core.alt.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:twinkle_rib')
    .addDefault(Text.translatable('tooltips.kubejs.twinkle_rib.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.twinkle_rib.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.twinkle_rib.alt.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:rough_infernal_dragon_skin')
    .addDefault(Text.translatable('tooltips.kubejs.rough_infernal_dragon_skin.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rough_infernal_dragon_skin.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:infernal_dragon_skin')
    .addDefault(Text.translatable('tooltips.kubejs.infernal_dragon_skin.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.infernal_dragon_skin.alt.1'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.infernal_dragon_skin.ctrl.1', Text.gold('5')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:immortal_volcanic_rock')
    .addDefault(Text.translatable('tooltips.kubejs.immortal_volcanic_rock.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.immortal_volcanic_rock.alt.1', Text.gold('100'), Text.gold('1')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:immortal_volcanic_crystal')
    .addDefault(Text.translatable('tooltips.kubejs.immortal_volcanic_crystal.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.immortal_volcanic_crystal.alt.1'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.immortal_volcanic_crystal.ctrl.1'))
)


RegistryOrganTooltip(new MultiStateTooltip('kubejs:broken_netherite_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.broken_netherite_muscle.default.1').gray())
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:netherite_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.netherite_muscle.default.1').gray())
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.netherite_muscle.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:worn_maledictus_wing')
    .addDefault(Text.translatable('tooltips.kubejs.worn_maledictus_wing.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.worn_maledictus_wing.alt.1', KeyActiveHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:maledictus_wing')
    .addDefault(Text.translatable('tooltips.kubejs.maledictus_wing.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.maledictus_wing.alt.1'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.maledictus_wing.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:corroded_leviathan_rib')
    .addDefault(Text.translatable('tooltips.kubejs.corroded_leviathan_rib.default.1').gray())
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:leviathan_rib')
    .addDefault(Text.translatable('tooltips.kubejs.leviathan_rib.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.leviathan_rib.alt.1'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.leviathan_rib.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:remnant_heart')
    .addDefault(Text.translatable('tooltips.kubejs.remnant_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.remnant_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.remnant_heart.alt.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:ancient_heart')
    .addDefault(Text.translatable('tooltips.kubejs.ancient_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ancient_heart.alt.1'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.ancient_heart.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.ancient_heart.ctrl.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:wizened_toxic_gland')
    .addDefault(Text.translatable('tooltips.kubejs.wizened_toxic_gland.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.wizened_toxic_gland.alt.1', KeyActiveHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:plump_toxic_gland')
    .addDefault(Text.translatable('tooltips.kubejs.plump_toxic_gland.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.plump_toxic_gland.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.plump_toxic_gland.alt.2'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.plump_toxic_gland.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:harbinger_lung')
    .addDefault(Text.translatable('tooltips.kubejs.harbinger_lung.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.harbinger_lung.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:sturdy_harbinger_lung')
    .addDefault(Text.translatable('tooltips.kubejs.sturdy_harbinger_lung.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.sturdy_harbinger_lung.alt.1'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.sturdy_harbinger_lung.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:rough_armor_plate')
    .addDefault(Text.translatable('tooltips.kubejs.rough_armor_plate.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rough_armor_plate.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:shining_armor_plate')
    .addDefault(Text.translatable('tooltips.kubejs.shining_armor_plate.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.shining_armor_plate.alt.1'))
    .addCtrl(AwakeRelicSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.shining_armor_plate.ctrl.1'))
)
