// priority: 800
ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:default_injection')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.default_injection.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.default_injection.shift.1', ChestcavityTypeHover, DefaultTypeHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:functional_entity_injection')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.functional_entity_injection.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.functional_entity_injection.shift.1', ChestcavityTypeHover, FunctionalEntityTypeHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gula_injection')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gula_injection.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gula_injection.shift.1', ChestcavityTypeHover, GulaTypeHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:rose_injection')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.rose_injection.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.rose_injection.shift.1', ChestcavityTypeHover, RoseTypeHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:revolution_machine_injection')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.revolution_machine_injection.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.revolution_machine_injection.shift.1', ChestcavityTypeHover, RevolutionMachineTypeHover))
)