
#容器尺寸配置
["箱子"]
	#Range: 1 ~ 20
	"行数" = 6
	#Range: 1 ~ 32
	"列数" = 9
	#随机容量组，格式: "行,列,权重" 如 ["3,9,50","6,9,30"], 留空则使用固定行列
	"随机容量" = []

["木桶"]
	#Range: 1 ~ 20
	"行数" = 6
	#Range: 1 ~ 32
	"列数" = 9
	#随机容量组，格式: "行,列,权重" 如 ["3,9,50","6,9,30"], 留空则使用固定行列
	"随机容量" = []

["潜影盒"]
	#Range: 1 ~ 20
	"行数" = 3
	#Range: 1 ~ 32
	"列数" = 9
	#随机容量组，格式: "行,列,权重" 如 ["3,9,50","6,9,30"], 留空则使用固定行列
	"随机容量" = []

["箱子矿车"]
	#Range: 1 ~ 20
	"行数" = 6
	#Range: 1 ~ 32
	"列数" = 9
	#随机容量组，格式: "行,列,权重" 如 ["3,9,50","6,9,30"], 留空则使用固定行列
	"随机容量" = []

