#Time required to progress by 1% during Shell creation (in ticks)
#Range: > 1
shellForgeCreationCooldown = 20
#Time required to progress by 1% during Shell decay (in ticks)
#Range: > 1
shellForgeDecayCooldown = 10
#Maximum energy storage capacity of the Centrifuge
#Range: > 1
centrifugeEnergyCapacity = 100000
#Energy consumed by the Centrifuge per tick
#Range: > 1
centrifugeEnergyUsage = 3000
#If enabled, the player will respawn in the nearest shell after death, even in hardcore mode. When disabled, death in hardcore mode remains permanent
transferIntoShellAfterDeath = true

