// priority: 500
ChestCavityEvents.organHoloFilterTags(event => {
    event.addTag('kubejs:appendix', 'tooltips.kubejs.tag.kubejs:appendix')
    event.addTag('kubejs:heart', 'tooltips.kubejs.tag.kubejs:heart')
    event.addTag('kubejs:intestine', 'tooltips.kubejs.tag.kubejs:intestine')
    event.addTag('kubejs:kidney', 'tooltips.kubejs.tag.kubejs:kidney')
    event.addTag('kubejs:liver', 'tooltips.kubejs.tag.kubejs:liver')
    event.addTag('kubejs:lung', 'tooltips.kubejs.tag.kubejs:lung')
    event.addTag('kubejs:muscle', 'tooltips.kubejs.tag.kubejs:muscle')
    event.addTag('kubejs:bone', 'tooltips.kubejs.tag.kubejs:bone')
    event.addTag('kubejs:gem', 'tooltips.kubejs.tag.kubejs:gem')
    event.addTag('kubejs:spine', 'tooltips.kubejs.tag.kubejs:spine')
    event.addTag('kubejs:spleen', 'tooltips.kubejs.tag.kubejs:spleen')
    event.addTag('kubejs:pancreas', 'tooltips.kubejs.tag.kubejs:pancreas')
    event.addTag('kubejs:stomach', 'tooltips.kubejs.tag.kubejs:stomach')
    event.addTag('kubejs:machine', 'tooltips.kubejs.tag.kubejs:machine')
    event.addTag('kubejs:magic', 'tooltips.kubejs.tag.kubejs:magic')
    event.addTag('kubejs:candy', 'tooltips.kubejs.tag.kubejs:candy')
    event.addTag('kubejs:rose', 'tooltips.kubejs.tag.kubejs:rose')
    event.addTag('kubejs:resource', 'tooltips.kubejs.tag.kubejs:resource')
    event.addTag('kubejs:revolution', 'tooltips.kubejs.tag.kubejs:revolution')
    event.addTag('kubejs:relics', 'tooltips.kubejs.tag.kubejs:relics')
    event.addTag('kubejs:legend', 'tooltips.kubejs.tag.kubejs:legend')
    event.addTag('kubejs:nature', 'tooltips.kubejs.tag.kubejs:nature')
    event.addTag('kubejs:basic', 'tooltips.kubejs.tag.kubejs:basic')
    event.addTag('kubejs:evolution', 'tooltips.kubejs.tag.kubejs:evolution')
    event.addTag('kubejs:food', 'tooltips.kubejs.tag.kubejs:food')
    event.addTag('kubejs:dragon', 'tooltips.kubejs.tag.kubejs:dragon')
    event.addTag('kubejs:ender', 'tooltips.kubejs.tag.kubejs:ender')
    event.addTag('kubejs:nether', 'tooltips.kubejs.tag.kubejs:nether')
    event.addTag('kubejs:infected', 'tooltips.kubejs.tag.kubejs:infected')
    event.addTag('kubejs:plant', 'tooltips.kubejs.tag.kubejs:plant')

})