// priority: 1000
// 杂项
StartupEvents.registry('item', event => {
    event.create('kubejs:sawdust').texture('kubejs:item/materials/sawdust').maxStackSize(64).burnTime(400)
    event.create('kubejs:badge').texture('kubejs:item/materials/badge').maxStackSize(1)
    event.create('kubejs:inactivated_neuron_tumor').texture('kubejs:item/materials/inactivated_neuron_tumor').maxStackSize(1)
    event.create('kubejs:dimensional_worm').texture('kubejs:item/materials/dimensional_worm').maxStackSize(1)
    event.create('kubejs:rainbow_compound').texture('kubejs:item/materials/rainbow_compound').maxStackSize(64)
    event.create('kubejs:blood_crystal').texture('kubejs:item/materials/blood_crystal').maxStackSize(64)
    event.create('kubejs:swollen_stamen').texture('kubejs:item/materials/swollen_stamen').maxStackSize(64)

    event.create('kubejs:relics_paper').texture('kubejs:item/materials/relics_paper').maxStackSize(64)
    event.create('kubejs:relics_metal').texture('kubejs:item/materials/relics_metal').maxStackSize(64)
    event.create('kubejs:relics_gem').texture('kubejs:item/materials/relics_gem').maxStackSize(64)
    event.create('kubejs:ancient_crystal').texture('kubejs:item/materials/ancient_crystal').maxStackSize(64)
    event.create('counterweight_gear').texture('kubejs:item/materials/counterweight_gear').tag('kubejs:unstable')
    event.create('oracle_gate').texture('kubejs:item/materials/oracle_gate').tag('kubejs:unstable')
    event.create('simulated_unit').texture('kubejs:item/materials/simulated_unit').tag('kubejs:unstable')
    event.create('redstone_capacitor').texture('kubejs:item/materials/redstone_capacitor')
    event.create('random_tick_spring').texture('kubejs:item/materials/random_tick_spring').tag('kubejs:unstable')
    event.create('structural_bolt').texture('kubejs:item/materials/structural_bolt')
    event.create('unstable_matter').texture('kubejs:item/materials/unstable_matter').fireResistant().tag('kubejs:unstable')
    event.create('refined_brass_ingot').texture('kubejs:item/materials/refined_brass_ingot').tag('kubejs:unstable')
    event.create('reverse_causality_chip').texture('kubejs:item/materials/reverse_causality_chip').tag('kubejs:unstable')
    event.create('timing_valve').texture('kubejs:item/materials/timing_valve').tag('kubejs:unstable')
    event.create('stable_substrate').texture('kubejs:item/materials/stable_substrate')
    event.create('amethyst_resonator').texture('kubejs:item/materials/amethyst_resonator')
    event.create('mantle_ore').texture('kubejs:item/materials/mantle_ore').maxStackSize(1)
    event.create('kubejs:relics_scroll_1').texture('kubejs:item/materials/relics_scroll_1').maxStackSize(1)
        .useDuration(itemStack => 40)
        .useAnimation('bow')
        .use((level, player, hand) => true)
        .releaseUsing((itemstack, level, entity) => itemstack)
        .finishUsing((itemstack, level, entity) => {
            if (level.isClientSide()) return Item.empty
            if (entity.isPlayer()) AStages.addStageToPlayer('relics_knowledge_1', entity)
            return Item.empty
        })
    event.create('kubejs:relics_scroll_2').texture('kubejs:item/materials/relics_scroll_2').maxStackSize(1)
        .useDuration(itemStack => 40)
        .useAnimation('bow')
        .use((level, player, hand) => true)
        .releaseUsing((itemstack, level, entity) => itemstack)
        .finishUsing((itemstack, level, entity) => {
            if (level.isClientSide()) return Item.empty
            if (entity.isPlayer()) AStages.addStageToPlayer('relics_knowledge_2', entity)
            return Item.empty
        })

    event.create('kubejs:task_singularity_1').texture('kubejs:item/materials/singularity/1').maxStackSize(1)
    event.create('kubejs:task_singularity_2').texture('kubejs:item/materials/singularity/2').maxStackSize(1)
    event.create('kubejs:task_singularity_3').texture('kubejs:item/materials/singularity/3').maxStackSize(1)
    event.create('kubejs:task_singularity_4').texture('kubejs:item/materials/singularity/4').maxStackSize(1)
    event.create('kubejs:task_singularity_5').texture('kubejs:item/materials/singularity/5').maxStackSize(1)
    event.create('kubejs:task_singularity_6').texture('kubejs:item/materials/singularity/6').maxStackSize(1)
    event.create('kubejs:task_singularity_7').texture('kubejs:item/materials/singularity/7').maxStackSize(1)
    event.create('kubejs:task_singularity_8').texture('kubejs:item/materials/singularity/8').maxStackSize(1)
    event.create('kubejs:task_singularity_9').texture('kubejs:item/materials/singularity/9').maxStackSize(1)
    event.create('kubejs:task_singularity_10').texture('kubejs:item/materials/singularity/10').maxStackSize(1)
    event.create('kubejs:task_singularity_11').texture('kubejs:item/materials/singularity/11').maxStackSize(1)
})