// priority: 800
ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_1')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('+1'), Text.lightPurple('+1')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_2')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('+2'), Text.lightPurple('+1')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_3')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('+4'), Text.lightPurple('+2')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_4')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('+10'), Text.lightPurple('+5')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_5')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('-1'), Text.lightPurple('+1')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_6')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('-2'), Text.lightPurple('+1')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_7')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('-5'), Text.lightPurple('+2')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_8')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('-10'), Text.lightPurple('+5')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_auxiliary_material_9')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_auxiliary_material.shift.2', Text.gold('-100'), Text.lightPurple('-100')))
)


ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_1')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_2')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('+1')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_3')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('+2')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_4')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('+3')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_5')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('+5')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_6')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('-1')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_7')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('-2')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_8')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('-3')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_awake_stone_9')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_awake_stone.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_awake_stone.shift.2', Text.gold('-5')))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:source_focus_crystal')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.source_focus_crystal.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.source_focus_crystal.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_extractant_material_1')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_extractant_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material_1.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_extractant_material_2')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_extractant_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material_2.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_extractant_material_3')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_extractant_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material_3.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_extractant_material_4')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_extractant_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material_4.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:gateways_extractant_material_5')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.gateways_extractant_material.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.gateways_extractant_material_5.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:eternal_miracle_ticket')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.eternal_miracle_ticket.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.eternal_miracle_ticket.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.eternal_miracle_ticket.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:incandescent_miracle_ticket')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.incandescent_miracle_ticket.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.incandescent_miracle_ticket.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.incandescent_miracle_ticket.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:artificial_miracle_ticket')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.artificial_miracle_ticket.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.artificial_miracle_ticket.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.artificial_miracle_ticket.shift.2'))
)


ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:primal_miracle_ticket')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.primal_miracle_ticket.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.primal_miracle_ticket.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.primal_miracle_ticket.shift.2'))
)
