// priority: 500
RegistryOrgan('kubejs:appendix').setRank(0).addScore('chestcavity:luck', 1).setCanSpawn(true)
RegistryOrgan('kubejs:intestine').setRank(0).addScore('chestcavity:nutrition', 1).setCanSpawn(true)
RegistryOrgan('kubejs:heart').setRank(0).addScore('chestcavity:health', 1).setCanSpawn(true)
RegistryOrgan('kubejs:kidney').setRank(0).addScore('chestcavity:filtration', 1).setCanSpawn(true)
RegistryOrgan('kubejs:liver').setRank(0).addScore('chestcavity:detoxification', 1).setCanSpawn(true)
RegistryOrgan('kubejs:lung').setRank(0).addScore('chestcavity:breath_recovery', 1).addScore('chestcavity:breath_capacity', 1).addScore('chestcavity:endurance', 1).setCanSpawn(true)
RegistryOrgan('kubejs:muscle').setRank(0).addScore('chestcavity:strength', 1).setCanSpawn(true)
RegistryOrgan('kubejs:rib').setRank(0).addScore('chestcavity:defense', 1).setCanSpawn(true)
RegistryOrgan('kubejs:spine').setRank(0).addScore('chestcavity:nerves', 1).setCanSpawn(true)
RegistryOrgan('kubejs:spleen').setRank(0).addScore('chestcavity:metabolism', 1).setCanSpawn(true)
RegistryOrgan('kubejs:stomach').setRank(0).addScore('chestcavity:digestion', 1).setCanSpawn(true)

RegistryOrgan('kubejs:animal_appendix').setRank(0).addScore('chestcavity:luck', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:animal_intestine').setRank(0).addScore('chestcavity:nutrition', 1).addScore('chestcavity:digestion', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:animal_heart').setRank(0).addScore('chestcavity:health', 1).setCanSpawn(true)
RegistryOrgan('kubejs:animal_kidney').setRank(0).addScore('chestcavity:filtration', 1).setCanSpawn(true)
RegistryOrgan('kubejs:animal_liver').setRank(0).addScore('chestcavity:detoxification', 1).setCanSpawn(true)
RegistryOrgan('kubejs:animal_lung').setRank(0).addScore('chestcavity:breath_recovery', 1).addScore('chestcavity:breath_capacity', 1).addScore('chestcavity:endurance', 1.5).setCanSpawn(true)
RegistryOrgan('kubejs:animal_muscle').setRank(0).addScore('chestcavity:strength', 1).setCanSpawn(true)
RegistryOrgan('kubejs:animal_rib').setRank(0).addScore('chestcavity:defense', 1).setCanSpawn(true)
RegistryOrgan('kubejs:animal_spine').setRank(0).addScore('chestcavity:nerves', 1).addScore('chestcavity:defense', 0.5).setCanSpawn(true)
RegistryOrgan('kubejs:animal_spleen').setRank(0).addScore('chestcavity:metabolism', 1).setCanSpawn(true)
RegistryOrgan('kubejs:animal_stomach').setRank(0).addScore('chestcavity:digestion', 1.5).setCanSpawn(true)
RegistryOrgan('kubejs:rumen').addScore('chestcavity:digestion', 1).addScore('chestcavity:nutrition', 1).setCanSpawn(true)

RegistryOrgan('kubejs:insect_lung').setRank(0).addScore('chestcavity:breath_recovery', 1).addScore('chestcavity:breath_capacity', 1).addScore('chestcavity:endurance', 1).setCanSpawn(true)
RegistryOrgan('kubejs:insect_muscle').setRank(0).addScore('chestcavity:strength', 1.5).setCanSpawn(true)
RegistryOrgan('kubejs:insect_intestine').setRank(0).addScore('chestcavity:nutrition', 1.5).setCanSpawn(true)
RegistryOrgan('kubejs:insect_heart').setRank(0).addScore('chestcavity:health', 1).setCanSpawn(true)
RegistryOrgan('kubejs:insect_caeca').setRank(0).addScore('chestcavity:metabolism', 1).setCanSpawn(true)
RegistryOrgan('kubejs:insect_stomach').setRank(0).addScore('chestcavity:digestion', 1).setCanSpawn(true)

RegistryOrgan('kubejs:gills').setRank(0).addScore('chestcavity:breath_recovery', -1).addScore('chestcavity:breath_capacity', 1).addScore('chestcavity:water_breath', 1).setCanSpawn(true)